# Generated by Django 4.2.6 on 2023-12-09 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('number_of_rooms', models.IntegerField()),
                ('number_of_bathrooms', models.IntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_guests', models.IntegerField()),
                ('number_of_beds', models.IntegerField()),
                ('images', models.ImageField(upload_to='rentals/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
