# Generated by Django 4.2.6 on 2023-12-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_rentals', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='address_city',
            field=models.CharField(default='Warsaw', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='address_street',
            field=models.CharField(default='Marszałkowska', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
