# Generated by Django 4.2.6 on 2023-12-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_rentals', '0003_rental_address_city_rental_address_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
