# Generated by Django 4.2.6 on 2023-12-23 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_rentals', '0004_reservation_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='images',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rentals/')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='add_rentals.rental')),
            ],
        ),
    ]
