# Generated by Django 4.2.6 on 2023-12-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_personaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='surname',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
    ]
